
baseURL = "https://simonwardjones.co.uk/"
enableRobotsTXT = true
googleAnalytics = "G-4D9QDJW5DC"
languageCode = "en-GB"
theme = "simon-blog-theme"
title = "Simon Ward-Jones"

[taxonomies]
category = "categories"

[params]
formspree = "https://formspree.io/xrgyqgjw"
twitter_handle = "@SimonWardJones"

[social]
email = "simonwardjones16@gmail.com"
facebook = "https://www.facebook.com/simon.wardjones"
github = "https://github.com/simonwardjones"
instagram = "https://www.instagram.com/simonw_j/"
linkedin = "https://www.linkedin.com/in/simon-ward-jones-357b16aa"
phone = "+447545629774"
twitter = "https://twitter.com/SimonWardJones"
